export const CHARACTERS = [
  {
    id: 1,
    name: 'Shredder',
    image: 'shredder',
    color: '#41105d',
  },
  {
    id: 2,
    name: 'Raphael',
    image: 'raphael3',
    color: '#930403',
  },
  {
    id: 3,
    name: 'Leonardo',
    image: 'leonardo2',
    color: '#205bbd', 
  },
  {
    id: 4,
    name: 'Rocksteady',
    image: 'rocksteady',
    color: '#dfbc96', 
  },
  {
    id: 5,
    name: 'Donatello',
    image: 'donatello',
    color: '#8b19a9',
  },
  {
    id: 6,
    name: 'Michelangelo',
    image: 'michelangelo',
    color: '#cf6215', 
  },
  {
    id: 7,
    name: 'Krang',
    image: 'krang1',
    color: '#e58196', 
  },
  {
    id: 8,
    name: 'REX-1',
    image: 'rex2',
    color: '#848aad', 
  },
];

export const QUOTES = [
  {
    id: 1,
    character_id: 1,
    quote: `"Espèce d'accident génétique !"`,
    season: '2',
    episode: '5',
    timer: '00:07:12',
  },
  {
    id: 2,
    character_id: 3,
    quote: `"Eh ben c'est une longue histoire...<br>— Alors vous la raconterez un autre jour !"`,
    season: '2',
    episode: '5',
    timer: '00:17:49',
  },
  {
    id: 3,
    character_id: 2,
    quote: `"Je connais très bien le responsable du musée d'histoire naturelle.<br>— ... Et alors ?"`,
    season: '2',
    episode: '5',
    timer: '00:18:11',
  },
  {
    id: 4,
    character_id: 4,
    quote: `"T'as déjà vu une créature aussi laide ?<br>— Oh oui alors, c'est tout à fait ton ancienne petite amie, on dirait sa soeur !"`,
    season: '2',
    episode: '6',
    timer: '00:15:37',
  },
  {
    id: 5,
    character_id: 6,
    quote: `"Oh mais c'est vraiment un rat-mulot celui-là !"`,
    season: '2',
    episode: '7',
    timer: '00:17:58',
  },
  {
    id: 6,
    character_id: 7,
    quote: `"Mais qu'est-ce qu'il y a, sautrelle malfaisante ?"`,
    season: '2',
    episode: '8',
    timer: '00:10:29',
  },
  {
    id: 7,
    character_id: 6,
    quote: `"Quoi ? Les deux caricatures ? Ces deux débiles ne savent même pas lire !"`,
    season: '2',
    episode: '9',
    timer: '00:04:59',
  },
  {
    id: 8,
    character_id: 1,
    quote: `"Si je vous répondais, vous n'y comprendriez absolument rien de toute façon, alors pourquoi perdre du temps pour rien ?"`,
    season: '2',
    episode: '9',
    timer: '00:05:18',
  },
  {
    id: 9,
    character_id: 2,
    quote: `"En plus d'être idots et laids, ce sont aussi des lâches..."`,
    season: '2',
    episode: '9',
    timer: '00:07:29',
  },
  {
    id: 10,
    character_id: 7,
    quote: `"C'est encore toi moucheron stupide..."`,
    season: '2',
    episode: '9',
    timer: '00:09:19',
  },
  {
    id: 11,
    character_id: 7,
    quote: `"Ah oui, coléoptère venimeux ?"`,
    season: '2',
    episode: '9',
    timer: '00:09:26',
  },
  {
    id: 12,
    character_id: 7,
    quote: `"Envoyez moi tout de suite le neuro-brouilleur que j'ai inventé !<br>— ... Pourquoi faire ?"`,
    season: '2',
    episode: '9',
    timer: '00:12:26',
  },
  {
    id: 13,
    character_id: 8,
    quote: `"Si vous vouliez que je reste tranquille, il ne fallait pas me faire lever."`,
    season: '2',
    episode: '10',
    timer: '00:06:14',
  },
  {
    id: 14,
    character_id: 8,
    quote: `"La police c'est moi. Je vous arrête pour arrestation intempestive !"`,
    season: '2',
    episode: '10',
    timer: '00:06:44', 
  },
  {
    id: 15,
    character_id: 3,
    quote: `"On va vous désintégrer vos circuits intégrés !"`,
    season: '2',
    episode: '10',
    timer: '00:15:47',
  },
  {
    id: 16,
    character_id: 8,
    quote: `"J'n'aurai jamais dû quitter le Texas, ma mère avait raison"`,
    season: '2',
    episode: '10',
    timer: '00:18:45', 
  },
];